data:
  datadir: null
  datafile: dataset_chewie_bl0
gpu_id: 0
logging:
  log_epochs: null
  log_interval: null
  log_model: false
neurons:
  g1: 1.2
  gin: 1.0
  gout: 0.1
  n1: 300
  noise: 0.1
  p_recurrent: 1.0
  tau: 0.05
outdir: null
regularization:
  alpha1: 0.0
  beta1: 0.0
  ccareg: false
  ccareg_components_end: 4
  ccareg_components_start: 1
  ccareg_start_trial: 0
  ccareg_type: sum_squared
  clipgrad: 0.2
  delta: 0.5
  gamma1: 0.0
  pcas_file: ''
  rel_end: 40
  rel_start: -5
seed: 20
simulation:
  sim_number: null
  network: RNN
timestamp: null
training:
  optimizer: SGD
  batch_size: 64
  lr: 100.0
  training_trials: 300
